# This is a basic workflow to help you get started with Actions

name: Deploy to Azure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGION: switzerlandnorth

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Copy files to the runner
        uses: actions/checkout@v4
      - name: Lint the Bicep Code
        run: az bicep build --file ./06_multi_deployment/main.bicep
      
  validate:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Copy files to the runner
        uses: actions/checkout@v4
      - uses: Azure/login@v2.1.0
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/arm-deploy@v2
        name: Run preflight validation
        with:
          scope: subscription
          region: ${{ env.REGION }}
          deploymentName: ${{ github.run_id }}
          template: ./06_multi_deployment/main.bicep
          parameters: azureRegion=${{ env.REGION }}
          deploymentMode: Validate